# Generated by Django 5.1.5 on 2025-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_created_at_faq_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
    ]
