# Generated by Django 5.1.5 on 2025-02-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_language_alter_faq_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='language',
        ),
    ]
