# Generated by Django 5.1.5 on 2025-02-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_remove_faq_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='question_bn',
            new_name='translated_question_bn',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_hi',
            new_name='translated_question_hi',
        ),
    ]
